spring:
  application:
    name: webstore

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  main:
    web-application-type: reactive

  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    root: INFO